name: "$(Build.DefinitionName) #$(Build.BuildId)"

trigger: none # Manual Publish
pr: none # GitHub Actions handle PRs

pool:
  vmImage: windows-latest

resources:
  repositories:
    - repository: self
      type: git

variables:
  - name: SIGN_FILE
    value: true

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build, Sign, and Pack

        variables:
          - group: Code Sign KV Auth

          - name: Configuration
            value: Release

          - name: slnPath
            value: src/Kentico.Xperience.Shopify.Libs.sln

        steps:
          - checkout: self
            submodules: true

          - task: DotNetCoreCLI@2
            displayName: Restore dotnet tools
            inputs:
              command: custom
              custom: tool
              arguments: restore
              workingDirectory: $(System.DefaultWorkingDirectory)

          - task: DotNetCoreCLI@2
            displayName: Restore dependencies
            inputs:
              command: restore
              projects: ${{ variables.slnPath }}
              feedsToUse: select
              restoreArguments: --locked-mode

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              projects: ${{ variables.slnPath }}
              configuration: ${{ variables.Configuration }}
              arguments: --no-restore
            env:
              AuthenticodeClientSecret: $(AuthenticodeClientSecret)
              # Roll-forward behavior set for AzureSignTool dotnet tool (see .config\dotnet-tools.json) which requires .Net 6.0 runtime
              DOTNET_ROLL_FORWARD: Major

          - template: steps.yml
            parameters:
              Configuration: $(Configuration)
              artifacts:
                - Shopify:
                  artifactName: "Kentico-Xperience-Shopify"
                  projectPath: "src/Kentico.Xperience.Shopify"
                - ShopifyRcl:
                  artifactName: "Kentico-Xperience-Shopify-Rcl"
                  projectPath: "src/Kentico.Xperience.Shopify.Rcl"

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - stage: PublishNuGetPackages
        displayName: Publish NuGet packages
        dependsOn: Build

        jobs:
          - deployment: PublishNuGetPackages
            displayName: Publish NuGet packages

            environment: integrations-release-nuget
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: none

                    - task: NuGetToolInstaller@1
                      displayName: Install latest nuget.exe
                      inputs:
                        versionSpec: ">=5.6"
                        checkLatest: true

                    - task: NuGetAuthenticate@1
                      displayName: NuGet Authenticate

                    - task: NuGetCommand@2
                      displayName: NuGet push
                      inputs:
                        command: push
                        packagesToPush: $(Pipeline.Workspace)/**/*.nupkg
                        nuGetFeedType: external
                        publishFeedCredentials: nuget.org
                        allowPackageConflicts: true
