//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Shopify
{
	/// <summary>
	/// Represents a content item of type <see cref="ProductVariant"/>.
	/// </summary>
	public partial class ProductVariant : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Shopify.ProductVariant";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// SKU.
		/// </summary>
		public string SKU { get; set; }


		/// <summary>
		/// Weight.
		/// </summary>
		public decimal Weight { get; set; }


		/// <summary>
		/// Image.
		/// </summary>
		public IEnumerable<Image> Image { get; set; }


		/// <summary>
		/// ShopifyVariantID.
		/// </summary>
		public string ShopifyVariantID { get; set; }


		/// <summary>
		/// ShopifyMerchandiseID.
		/// </summary>
		public string ShopifyMerchandiseID { get; set; }


		/// <summary>
		/// ShopifyProductID.
		/// </summary>
		public string ShopifyProductID { get; set; }
	}
}