//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Shopify
{
	/// <summary>
	/// Represents a content item of type <see cref="Image"/>.
	/// </summary>
	public partial class Image : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Shopify.Image";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// ImageAsset.
		/// </summary>
		public ContentItemAsset ImageAsset { get; set; }


		/// <summary>
		/// ImageDescription.
		/// </summary>
		public string ImageDescription { get; set; }


		/// <summary>
		/// ShopifyImageID.
		/// </summary>
		public string ShopifyImageID { get; set; }
	}
}