//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Shopify
{
	/// <summary>
	/// Represents a content item of type <see cref="Product"/>.
	/// </summary>
	public partial class Product : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Shopify.Product";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// Description.
		/// </summary>
		public string Description { get; set; }


		/// <summary>
		/// ShopifyProductID.
		/// </summary>
		public string ShopifyProductID { get; set; }


		/// <summary>
		/// Images.
		/// </summary>
		public IEnumerable<Image> Images { get; set; }


		/// <summary>
		/// Variants.
		/// </summary>
		public IEnumerable<ProductVariant> Variants { get; set; }


		/// <summary>
		/// Parameters.
		/// </summary>
		public string Parameters { get; set; }
	}
}